project_id = "cufykawssrjdftlffuod"

[functions.create-admin-user]
verify_jwt = false

[functions.chat-with-ai]
verify_jwt = false

[functions.send-application-notification]
verify_jwt = false

[functions.send-webinar-confirmation]
verify_jwt = false

[functions.send-webinar-thankyou]
verify_jwt = false