project_id = "cufykawssrjdftlffuod"

[functions.create-admin-user]
verify_jwt = false

[functions.chat-with-ai]
verify_jwt = false

[functions.send-application-notification]
verify_jwt = false

[functions.send-webinar-confirmation]
verify_jwt = false

[functions.send-webinar-thankyou]
verify_jwt = false

[functions.test-zapier-webhook]
verify_jwt = false

[functions.send-to-zapier]
verify_jwt = false

[functions.email-drip-campaign]
verify_jwt = false

[functions.sms-notification]
verify_jwt = false

[functions.send-guide-confirmation]
verify_jwt = false